name: Auto Post Cambodia Result

on:
  schedule:
    - cron: '51 4 * * *'  # 11:51 WIB (UTC+7)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          WP_API_URL: ${{ secrets.WP_API_URL }}
        run: |
          python run.py
